version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iitb
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    image: racchittt/iitb-backend:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: iitb-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iitb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - backend-network

  frontend:
    image: racchittt/iitb-frontend:latest
    container_name: iitb-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    

